# Generated by Django 3.0.5 on 2021-11-06 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('requestedLeaves_text', models.TextField()),
                ('whyLeaves', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Resolved')], max_length=10)),
                ('requestedLeaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('emp_status', models.CharField(max_length=70)),
                ('salary', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.IntegerField()),
                ('skill_set', models.TextField()),
                ('image', models.ImageField(upload_to='HR/static/HR')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
